---
version: '3.6'

x-besu-bootnode-def:
  &besu-bootnode-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./.env
  entrypoint:
    - /bin/bash
    - -c
    - |
      /opt/besu/bin/besu public-key export --to=/tmp/bootnode_pubkey;
      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --genesis-file=/config/genesis.json \
      --node-private-key-file=/opt/besu/keys/key ;


#      --p2p-host=$$(hostname -i) \

services:
  bc31node1:
    << : *besu-bootnode-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=bc31node1,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./bc31:/config
      - ./keys:/opt/besu/keys
      #- ./logs/bc31:/tmp/besu
    ports:
      - 8310:8545/tcp
    networks:
      gpact-test1:
        ipv4_address: 172.16.239.11

  bc32node1:
    << : *besu-bootnode-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=bc32node1,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./bc32:/config
      - ./keys:/opt/besu/keys
      #- ./logs/bc32:/tmp/besu
    ports:
      - 8320:8545/tcp
    networks:
      gpact-test1:
        ipv4_address: 172.16.239.12

  bc33node1:
    << : *besu-bootnode-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=bc33node1,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./bc33:/config
      - ./keys:/opt/besu/keys
      #- ./logs/bc33:/tmp/besu
    ports:
      - 8330:8545/tcp
    networks:
      gpact-test1:
        ipv4_address: 172.16.239.13

  bc34node1:
    << : *besu-bootnode-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=bc34node1,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./bc34/config
      - ./keys:/opt/besu/keys
      #- ./logs/bc34:/tmp/besu
    ports:
      - 8340:8545/tcp
    networks:
      gpact-test1:
        ipv4_address: 172.16.239.14

  bc35node1:
    << : *besu-bootnode-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=bc35node1,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./bc35/config
      - ./keys:/opt/besu/keys
      #- ./logs/bc35:/tmp/besu
    ports:
      - 8350:8545/tcp
    networks:
      gpact-test1:
        ipv4_address: 172.16.239.15

networks:
  gpact-test1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
